apiVersion: apps/v1
kind: Deployment
metadata:
    name: jupyter-dp
    namespace: jupyter ## criado no arquivo jupyter-ns.yaml
    labels:
        app: jupyter-app
spec:
    replicas: 3 # 3 replicas
    selector:
        matchLabels:
            app: jupyter-pods # Seleciona os pods com label app=jupyter-pods
    template: # Template para criar os pods
        metadata:
            labels:
                app: jupyter-pods
        spec:
            containers: # Container com a aplicação
                - name: jupyter-container
                  image: jupyter/minimal-notebook:2022-12-05
                  ports:
                      - containerPort: 8888
                  command: ['start-notebook.sh']
                  args: ["--NotebookApp.token=''"]
