kind: Pod
apiVersion: v1
metadata:
    name: pod-cm-vol
spec:
    containers:
        - name: my-container
          image: nginx
          envFrom:
              - configMapRef: ## referencia o config map
                    name: my-cm
          volumeMounts:
              - name: my-vol
                mountPath: '/etc/my-vol' ## monta o volume no path /etc/my-vol para o container acessar.
                readOnly: true ## read only apenas para guardar as variáveis de ambiente.

    volumes:
        - name: my-vol
          configMap: ## associa o volume com o config map.
              name: my-cm
