apiVersion: v1
kind: Secret
metadata:
    name: my-secret
data: #todos os valores estão em base64. Para converter para texto, use o comando echo -n 'valor' | base64 -d, para converter para base64, use echo -n 'valor' | base64
    user: YWRtaW4=
    pass: TXktcGFzcy0xMjM=
stringData: #não é necessário converter para base64, o kubernetes faz isso automaticamente
    token: my-token
immutable: true #não pode ser alterado
