apiVersion: v1
kind: Secret
metadata:
  name: my-secret
data:
  user: YWRtaW4=
  pass: TXktcGFzcy0xMjM=
stringData:
  my-database-name: mysql
---

kind: Pod
apiVersion: v1
metadata:
  name: pod-secret-vol-env
spec:
  containers:
  - name: my-container
    image: nginx
    envFrom:
    - secretRef:
        name: my-secret
    volumeMounts:
    - name: my-vol
      mountPath: "/etc/my-vol"
      readOnly: true

  volumes:
  - name: my-vol
    secret:
      secretName: my-secret

