apiVersion: v1
kind: Service
metadata:
    name: my-external-database-service
    namespace: production
spec:
    type: ExternalName
    externalName: my.database.example.com # colocar a url do banco de dados
