apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: my-daemonset
    labels:
        app: frontend

spec:
    template:
        metadata:
            name: pod-web-server
            labels:
                apps: my-app
                tier: frontend
        spec:
            containers:
                - name: my-container-nginx
                  image: nginx
            nodeName: minikube # nome do worker node onde o pod será criado
    selector:
        matchLabels:
            apps: my-app
