apiVersion: v1
kind: Pod
metadata:
    name: my-pod-webserver
    # namespace: backend
    labels:
        apps: my-app
        tier: frontend
spec: #informações para o container a ser criado dentro do pod, o nome e a imagem que será baixada.
    containers:
        - name: my-container-nginx
          image: nginx
