apiVersion: v1
kind: Service
metadata:
    name: svc-sts # service statefulset
spec:
    ports:
        - port: 80
    clusterIP: None # não tem ip, pois é um serviço headless
    selector:
        app: nginx-app-pods
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: my-sts
spec:
    selector:
        matchLabels: # label dos pods que serão criados
            app: nginx-app-pods
    serviceName: 'svc-sts'
    replicas: 3
    template:
        metadata:
            labels: # label do pod que será criado
                app: nginx-app-pods
        spec: # spec do template
            containers: # container do pod
                - name: my-container # nome do container
                  image: nginx:1.23.1 # imagem do container
                  volumeMounts:
                      - name: my-pv
                        mountPath: /usr/share/nginx/html
    volumeClaimTemplates: # template do volume Dinâmico, todo pod será atribuído ao volume.
        - metadata:
              name: my-pv
          spec:
              accessModes: ['ReadWriteOnce']
              resources:
                  requests:
                      storage: 1Gi
