apiVersion: v1
kind: Pod
metadata:
    name: redis-pod
spec:
    containers:
        - name: redis-container
          image: redis
          volumeMounts: # montar o volume
              - name: 'cache-storage' # nome do volume
                mountPath: '/my-volume' # caminho onde o volume será montado dentro do container

    # especificar os volues
    volumes:
        - name: cache-storage
          emptyDir: {}
