apiVersion: v1
kind: Pod
metadata:
    name: redis-pod
spec:
    containers:
        - name: redis-container
          image: redis
          volumeMounts:
              - mountPath: '/my-data' # caminho dentro do container que será a referência para o volume de fora
                name: 'my-hostpath-vol'

    volumes:
        - name: 'my-hostpath-vol'
          hostPath:
              path: '/var/lib/2-persist' # caminho do volume no host path do worker node. Apenas isso já é necessário para ser criado dentro do worker node.
