apiVersion: v1
kind: Pod
metadata:
  name: pod-apache # 10.244.0.10
spec:
  containers:
  - name: my-apache
    image: httpd

---

apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx # 10.244.0.11
spec:
  containers:
  - name: my-nginx
    image: nginx
