apiVersion: v1
kind: Endpoints
metadata:
    name: my-endpoints-service
subsets: # subconjunto de endpoints
    - addresses:
          - ip: 77.68.88.76 # IIS
          # - ip: 10.244.0.178 # Apache
          # - ip: 10.244.0.179 # Nginx
      ports:
          - port: 80

---
apiVersion: v1
kind: Service
metadata:
    name: my-endpoints-service
spec:
    ports:
        - protocol: TCP
          port: 80
          targetPort: 80
